### ISSUE TITLE
Payrespects error in 0.2

### ISSUE THREAD

**Issue by crazybmanp** [crazybmanp/RyuZU-Bot#54]
Ignoring exception in command payrespects
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pi/OverPub Bot/Memes/__init__.py", line 91, in payrespects
    sdb = self.f_server_db[ctx.message.server.id]
KeyError: '265354023333265418'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: '265354023333265418'

**Comment by crazybmanp** [comment]
This error may have something to do with using on_ready to mount databases
