### ISSUE TITLE
quote delete <quotenum> Doesn't work

### ISSUE THREAD

**Issue by razage** [crazybmanp/RyuZU-Bot#64]
I tried deleting quote 102 several times and it hasn't worked. I'm sure some kind of error came up, but only you can check that.

**Comment by crazybmanp** [comment]
i was going to go ahead and fix that internally, but i will have to check into this bug

**Comment by crazybmanp** [comment]
ne 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pi/RyuZU/Quotes/__init__.py", line 69, in delete
    sdb.remove(eid=quotenum)
TypeError: remove() got an unexpected keyword argument 'eid'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: remove() got an unexpected keyword argument 'eid'
